version: 2.1

orbs:
  slack: circleci/slack@4.2.1

executors:
  default:
    working_directory: ~/ssml-tsx
    docker:
      - image: cimg/node:14.15.5

commands:
  restore_dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum ".node-version" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}-{{ checksum ".node-version" }}-
      - run:
          name: Yarn
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
  save_dependencies:
    steps:
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-{{ arch }}-{{ checksum ".node-version" }}-{{ checksum "yarn.lock" }}

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout:
          path: ~/ssml-tsx
      - restore_dependencies
      - save_dependencies
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
  release:
    executor:
      name: default
    steps:
      - checkout:
          path: ~/ssml-tsx
      - restore_dependencies
      - run:
          name: yarn release
          command: yarn release

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - slack/on-hold:
          channel: ${SLACK_CHANNEL}
          context: slack-orb
          requires:
            - test
      - release-approval:
          type: approval
          requires:
            - slack/on-hold
      - release:
          context: release-timetree-sdk
          requires:
            - release-approval
