version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  default:
    working_directory: ~/ssml-tsx
    docker:
      - image: circleci/node:12.18.1

commands:
  restore_dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum ".node-version" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-{{ arch }}
            - v1-dependencies-
      - run:
          name: Yarn
          command: yarn
  save_dependencies:
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum ".node-version" }}-{{ checksum "yarn.lock" }}

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout:
          path: ~/ssml-tsx
      - restore_dependencies
      - save_dependencies
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
  release:
    executor:
      name: default
    steps:
      - checkout:
          path: ~/ssml-tsx
      - restore_dependencies
      - run:
          name: yarn release
          command: yarn release

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  test_and_release:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - slack/approval-notification:
          channel: ${SLACK_CHANNEL}
          context: release-timetree-sdk
          requires:
            - test
      - release-approval:
          type: approval
          requires:
            - slack/approval-notification
      - release:
          context: release-timetree-sdk
          requires:
            - release-approval
